steps:

  - id: 'Svelte / Hugo Build Prod'
    name: 'node'
    script: |
      #! /usr/bin/env bash

      # Build Svelte apps and move generated files into position
      ./svelte/build.sh

      # install hugo "extended"
      HUGO_VERSION=0.147.9
      wget https://github.com/gohugoio/hugo/releases/download/v${HUGO_VERSION}/hugo_extended_${HUGO_VERSION}_linux-amd64.deb -O /tmp/hugo.deb

      apt install /tmp/hugo.deb

      # Build the prod version of the site (this will omit content where the front matter specifies Draft: true)
      hugo --source=./hugo --destination=/workspace/hugo/public --logLevel=debug

  - id: 'Firebase (re)Deploy ALL'
    name: gcr.io/$PROJECT_ID/firebase
    env:
      - 'PROJECT_ID=$PROJECT_ID'
    script: |
      firebase deploy --non-interactive  --force --project=${PROJECT_ID}

logsBucket: 'doradotdev-cloudbuild-logs'
