steps:
  - name: gcr.io/$PROJECT_ID/hugo
    id: 'hugo'
    args: [
      "-v", "-s", "./hugo",
      "-d", "/workspace/hugo/public",
      "--debug"
      ]

  - name: gcr.io/$PROJECT_ID/firebase
    env:
      - "_PR_NUMBER=$_PR_NUMBER"
    script: |
      PREVIEW_CHANNEL="PR$_PR_NUMBER"
      firebase hosting:channel:deploy $PREVIEW_CHANNEL --project=$PROJECT_ID
      
      # get the url of the deployed site
      # (it returns in format `i  hosting:channel: https://<url>`)
      CHANNEL_DATA="$(firebase hosting:channel:open $PREVIEW_CHANNEL)"

      # extract the URL from the channel data and save it to /workspace
      echo "${CHANNEL_DATA##* }" > /workspace/preview-url.txt
      cat /workspace/preview-url.txt

# add preview URL as a status check
# prereq: a github token exists in Secret manager named with the name specified by `github-token-secret-name`
# the token must have access: `repo:status` (or `repo:all` for a private repo)
  - name: 'gcr.io/${PROJECT_ID}/pr-status-poster'
    env:
      - "COMMIT_SHA=$COMMIT_SHA"
      - "REPO_NAME=$REPO_NAME"
      - "PROJECT_ID=$PROJECT_ID"
    script: |
      python /app/set-check-status.py \
        --project-id ${PROJECT_ID} \
        --repo-name davidstanke/${REPO_NAME} \
        --commit-sha ${COMMIT_SHA} \
        --target-url "$(cat /workspace/preview-url.txt)" \
        --github-token-secret-name github_token

