steps:
  - name: gcr.io/$PROJECT_ID/hugo
    script: |
      # Build draft site and published site
      hugo -D -v -s ./hugo -d /workspace/hugo/draft --debug

  - name: gcr.io/$PROJECT_ID/firebase
    env:
      - "_PR_NUMBER=$_PR_NUMBER"
    script: |
      PREVIEW_CHANNEL="PR$_PR_NUMBER"
      firebase hosting:channel:deploy $PREVIEW_CHANNEL --project=$PROJECT_ID --only draft
      
      # get the url of this preview channel, within the "draft" site
      # (it returns in format `i  hosting:channel: https://<url>`)
      CHANNEL_DATA="$(firebase hosting:channel:open $PREVIEW_CHANNEL --site draft-dora-dev)"

      # extract the URL from the channel data and save it to /workspace
      echo "${CHANNEL_DATA##* }" > /workspace/preview-url.txt
      cat /workspace/preview-url.txt

  - name: 'ubuntu'
    script: |
      #!/usr/bin/env bash
      
      # install the github CLI (per instructions at https://github.com/cli/cli/blob/trunk/docs/install_linux.md)
      type -p curl >/dev/null || (sudo apt update && sudo apt install curl -y)
      curl -fsSL https://cli.github.com/packages/githubcli-archive-keyring.gpg | sudo dd of=/usr/share/keyrings/githubcli-archive-keyring.gpg \
      && sudo chmod go+r /usr/share/keyrings/githubcli-archive-keyring.gpg \
      && echo "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/githubcli-archive-keyring.gpg] https://cli.github.com/packages stable main" | sudo tee /etc/apt/sources.list.d/github-cli.list > /dev/null \
      && sudo apt update \
      && sudo apt install gh -y

      gh version




# # add preview URL as a status check
# # prereq: a github token exists in Secret manager named with the name specified by `github-token-secret-name`
# # the token must have access: `repo:status` (or `repo:all` for a private repo)
#   - name: 'gcr.io/${PROJECT_ID}/pr-status-poster'
#     env:
#       - "COMMIT_SHA=$COMMIT_SHA"
#       - "REPO_NAME=$REPO_NAME"
#       - "PROJECT_ID=$PROJECT_ID"
#     script: |
#       python /app/set-check-status.py \
#         --project-id ${PROJECT_ID} \
#         --repo-name dora-team/${REPO_NAME} \
#         --commit-sha ${COMMIT_SHA} \
#         --target-url "$(cat /workspace/preview-url.txt)" \
#         --github-token-secret-name github_token

